version: "3"

services:
  postgres-alan:
    image: postgres:12-alpine
    environment:
      - IDIARIO_POSTGRES_START=${IDIARIO_POSTGRES_START}
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE_ENV}
    command: sh -c "[ \"$$IDIARIO_POSTGRES_START\" = true ] && echo 'PostgreSQL service is disabled!!' || docker-entrypoint.sh postgres"
    volumes:
      - ${VOL_PG_DATA}:/var/lib/postgresql/12/main
  i-diario-all:
    build:
      context: ./
      args:
        IDIARIO_VERSION: ${IDIARIO_VERSION_ENV}
    image: i-diario-all
    environment:
      - IDIARIO_POSTGRES_START=${IDIARIO_POSTGRES_START}
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      #- IDIARIO_DISABLE=${IDIARIO_DISABLE_ENV}
      - IDIARIO_ENVIRONMENT=${IDIARIO_ENVIRONMENT_ENV}
      - IDIARIO_SECRET_KEY=${IDIARIO_SECRET_KEY_ENV}
      - IDIARIO_DOMAIN=${IDIARIO_DOMAIN_ENV}
      - IDIARIO_NAME=${IDIARIO_NAME_ENV}
      - IDIARIO_PASS=${IDIARIO_PASS_ENV}
      - IDIARIO_DATABASE=${POSTGRES_DATABASE_ENV}
      - SIDEKIQ_PASS=${SIDEKIQ_PASS_ENV}
      #- SMTP_DOMAIN=${IDIARIO_SMTP_DOMAIN}
      - SMTP_HOST=${IDIARIO_SMTP_ADDRESS}
      - SMTP_PORT=${IDIARIO_SMTP_PORT}
      - SMTP_LOGIN=${IDIARIO_SMTP_USER_NAME}
      - SMTP_PASSWORD=${IDIARIO_SMTP_PASSWORD}
    volumes:
      - ${VOL_PG_DATA}:/var/lib/postgresql/12/main
      - ${VOL_BOX}:/box
    ports:
      - 3000:3000
